# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YiShopkeeper' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for YiShopkeeper
pod 'Masonry'
pod 'AFNetworking'
pod 'FMDB'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'HexColors'
pod 'SVProgressHUD'
pod 'IQKeyboardManager'
pod 'MJExtension'
pod 'LGAlertView'
pod 'LFMediaEditingController'
pod 'YMCitySelect'
pod 'BaiduMapKit' #百度地图SDK
pod 'YYKit'
pod 'RongCloudIM/IMLib', '~> 2.8.3'
pod 'RongCloudIM/IMKit', '~> 2.8.3'
#pod 'RongCloudIMKit'
#pod 'MLeaksFinder'
pod 'UMengUShare/UI'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/Email'
pod 'UMengUShare/Social/SMS'
pod 'JPush'
end
